### ISSUE TITLE
Generate correct URLs for files with .page extension in sitemap

### ISSUE THREAD

**Issue by blazemachine** [VirtoCommerce/vc-module-sitemaps#4]
For static content on the new site version of virtocommerce.com now is using extra file extension - page. Need to add a logic for sitemap loading. This logic should consider .page files for sitemap generation. JSON property "permalink" from first block in .page file need for url in sitemap.

Below is an example .page file:
[
    {
        "type": "settings",
        "title": "Download our B2B Enterprise Ecommerce Architecture Details",
        "permalink": "download-arch-guidelines",
        "id": 1,
        "header": "Download Virto Commerce's Architectural Guidelines"
    },
    {
        "id": 2,
        "type": "text-over-image",
        "name": null,
        "title": "Virto Commerce Architectural Guidelines ",
        "subTitle": " ",
        "image": {
            "url": "https://vcpro.blob.core.windows.net/blogs/hero (10).png"
        },
        "content": "<p>Get a bird&#39;s eye view of our technology&nbsp;</p>\n",
        "url1": null,
        "url2": null,
        "noTop": null,
        "noBottom": null,
        "noPad": null,
        "headerType": "h1",
        "titleAlignment": null
    }
]

**Comment by akak1977** [comment]
Released: https://github.com/VirtoCommerce/vc-module-sitemaps/releases/tag/v1.1.7
