### ISSUE TITLE
Performance problem in EstateSpain project.

### ISSUE THREAD

**Issue by vladimir-buravlev** [VirtoCommerce/vc-module-sitemaps#6]
We have 18k+ records in product catalog, and when we want to base on sitemap index file "sitemap.xml" to obtain the name our product files - we are faced with the problem... When we try generate sitemap index file "sitemap.xml", it lasts more then 10 minutes :(

Now we have solved this problem using hard names for "product--1.xml" and "product--2.xml" files, but this is not universal, if in the future the number of products exceeds 20k - again it will be necessary to rewrite the names by hand.

If it may be somehow possible to improve the performance of the sitemap generation algorithm, it would be great.

**Comment by OlegoO** [comment]
The release https://github.com/VirtoCommerce/vc-module-sitemaps/releases/tag/3.810.0 introduces the ability to export sitemaps to store assets. You can export sitemaps files to assets either manually or by schedule.
